<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <NoWarn>$(NoWarn);SYSLIB5001</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>FAI.Onnx.Tests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.ML.OnnxRuntime.Managed" Version="1.24.1" />
        <ProjectReference Include="..\FAI.Core\FAI.Core.csproj" />
        <ProjectReference Include="..\FAI.Core.Extensions.DI\FAI.Core.Extensions.DI.csproj" />
        <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.400" />
    </ItemGroup>

</Project>
